### ISSUE TITLE
Panic if specified macro used in code

### ISSUE THREAD

**Issue by hankbao** [coder543/libasm#1]
Panic if `#![allow(clippy::cast_ptr_alignment)]` used in code.

```shell
--- stderr
thread 'main' panicked at 'Unable to parse file: ParseError(Some("failed to parse crate: failed to parse all tokens"))', src\libcore\result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

The terminal process terminated with exit code: 1
```

**Comment by coder543** [comment]
This crate was mainly meant for demo purposes, not to be used in actual projects. If you find a solution, I'm happy to accept a PR!

**Comment by hankbao** [comment]
Alright then. Thank you for providing this crate anyway.

Close for now.
